// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RemoteDebug
{
    internal sealed partial class Vsix
    {
        public const string Id = "RemoteDebug.adc97100-7942-4f90-aed5-1f8cd6a65186";
        public const string Name = "RemoteDebug";
        public const string Description = @"RemoteDebug";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "dev-joshi";
        public const string Tags = "";
    }
}
